using System.Collections.Concurrent;
using System.Text.Json;
using System.Text.Json.Nodes;
using System.Reflection;
using Microsoft.AspNetCore.Hosting.Server;
using Microsoft.AspNetCore.Hosting.Server.Features;
using SeMind.Assistant.Gateway;

// Isolated fake transports: never connects to an actual game/model/service.
const string steam = "76561198000000101", otherSteam = "76561198000000102", server = "component-host", run = "component-run";
string world = Guid.NewGuid().ToString(), root = "D:/semind-librechat/temp/bridge-checks-" + Guid.NewGuid().ToString("N");
Directory.CreateDirectory(root);
string key = Guid.NewGuid().ToString("N") + Guid.NewGuid().ToString("N");
File.WriteAllText(Path.Combine(root,"game.key.json"), new JsonObject{["game_ai_key"]=key}.ToJsonString());
var builder=WebApplication.CreateBuilder();builder.Logging.ClearProviders();builder.WebHost.UseUrls("http://127.0.0.1:0");
var app=builder.Build();
var nativeCalls=new ConcurrentDictionary<string,int>();
var runs=new ConcurrentDictionary<string,JsonObject>();
var steers=new ConcurrentDictionary<string,ConcurrentQueue<string>>();
var completions=new ConcurrentDictionary<string,TaskCompletionSource<bool>>();
var canceled=new ConcurrentQueue<string>();
bool foreignActor=false;
async Task<JsonObject> Body(HttpContext context)=>await JsonNode.ParseAsync(context.Request.Body) as JsonObject??throw new Exception("Invalid test body");
app.MapPost("/actor", async(HttpContext context)=>{
  var body=await Body(context);
  if(context.Request.Headers["X-SeMind-Key"]!=key)throw new Exception("Missing native authentication");
  return Results.Json(new {ok=true,result=new{server_id=server,world_id=world,steam_id=foreignActor?otherSteam:body["steam_id"]!.GetValue<string>(),identity_id="1",source_run_id=run}});
});
app.MapPost("/live", async(HttpContext context)=>{
  var body=await Body(context);string operation=body["operation_id"]!.GetValue<string>();
  nativeCalls.AddOrUpdate(operation,1,(_,n)=>n+1);
  if(body["server_id"]!.GetValue<string>()!=server||body["world_id"]!.GetValue<string>()!=world||body["steam_id"]!.GetValue<string>()!=steam)throw new Exception("Scope crossed actor");
  return Results.Json(new{ok=true,result=new{observed=true}});
});
app.MapPost("/tasks/cancel",async(HttpContext context)=>{canceled.Enqueue((await Body(context))["task_id"]!.GetValue<string>());return Results.Json(new{ok=true});});
app.MapPost("/internal/semind/game/cancel",async(HttpContext context)=>{var body=await Body(context);if(completions.TryGetValue(body["task_id"]!.GetValue<string>(),out var value))value.TrySetResult(true);return Results.Json(new{canceled=true});});
app.MapPost("/internal/semind/game/steer",async(HttpContext context)=>{var body=await Body(context);string id=body["task_id"]!.GetValue<string>();steers.GetOrAdd(id,_=>new()).Enqueue(body["input"]!["input_id"]!.GetValue<string>());return Results.Json(new{accepted=true});});
app.MapPost("/internal/semind/game/run",async(HttpContext context)=>{
  var body=await Body(context);string id=body["task_id"]!.GetValue<string>();runs[id]=body;
  if(id.StartsWith("held-"))await completions.GetOrAdd(id,_=>new(TaskCreationOptions.RunContinuationsAsynchronously)).Task.WaitAsync(context.RequestAborted);
  var consumed=steers.TryGetValue(id,out var queue)?queue.ToArray():Array.Empty<string>();
  return Results.Json(new{ok=true,text="isolated reply "+id,message_id=id+"-reply",selected_agent_id="owner-selected-agent",steering_ids=consumed,history=new object[]{new{type="human",data=new{content=id}},new{type="ai",data=new{content="reply"}}}});
});
await app.StartAsync();string url=app.Services.GetRequiredService<IServer>().Features.Get<IServerAddressesFeature>()!.Addresses.Single();
Environment.SetEnvironmentVariable("SEMIND_GAME_SERVER_ID",server);Environment.SetEnvironmentVariable("SEMIND_GAME_LIVE_URL",url);Environment.SetEnvironmentVariable("SEMIND_LIBRECHAT_URL",url);
Environment.SetEnvironmentVariable("SEMIND_GAME_KEY_PATH",Path.Combine(root,"game.key.json"));Environment.SetEnvironmentVariable("SEMIND_INTERNAL_KEY",key);
Environment.SetEnvironmentVariable("SEMIND_ASSISTANT_STATE_ROOT",Path.Combine(root,"state"));Environment.SetEnvironmentVariable("SEMIND_ASSISTANT_LIBRARY_ROOT",Path.Combine(root,"scripts"));
var checks=new JsonArray();
void Check(bool condition,string name){if(!condition)throw new Exception("FAILED "+name);checks.Add(new JsonObject{["check"]=name,["passed"]=true});}
async Task Wait(Func<bool> predicate){for(int i=0;i<200;i++){if(predicate())return;await Task.Delay(25);}throw new Exception("Test boundary timeout");}
async Task Error(Func<Task> action,string code,string name){try{await action();throw new Exception("Missing error "+name);}catch(BrokerError error){Check(error.Code==code,name);}}
GameBridge.Input Input(string id,long sequence,string? owner=null)=>new(){InputId=id,ServerId=server,WorldId=world,SteamId=owner??steam,IdentityId="1",Text="synthetic transport only",SourceRunId=run,SourceSequence=sequence};
JsonObject Json(object result)=>JsonSerializer.SerializeToNode(result,Wire.Json) as JsonObject??throw new Exception("Invalid serialized test result");
var bridge=new GameBridge();bridge.Authenticate(key);bridge.Authenticate("Bearer "+key,true);
await Error(()=>{bridge.Authenticate("wrong");return Task.CompletedTask;},"unauthorized","native-key-rejected");
var voice=Input("voice-rejected",100);voice.Modality="voice";await Error(async()=>{await bridge.Accept(voice,default);},"invalid_game_input","text-only-contract-rejects-voice");
foreignActor=true;await Error(async()=>{await bridge.Accept(Input("foreign-actor",101),default);},"game_actor_changed","native-authority-cannot-change-actor");
await Error(async()=>{await bridge.PrepareDetached(new JsonObject{["task_id"]="foreign-detached",["world_id"]=world,["steam_id"]=steam},default);},"game_actor_changed","detached-native-authority-cannot-change-actor");foreignActor=false;
await bridge.Accept(Input("first",1),default);
Check(Json(await bridge.Accept(Input("first",1),default))["duplicate"]!.GetValue<bool>(),"input-id-deduplication");
var changed=Input("first",1);changed.Text="changed";await Error(async()=>{await bridge.Accept(changed,default);},"input_id_conflict","input-id-content-conflict");
await Error(async()=>{await bridge.Accept(Input("collision",1),default);},"source_sequence_conflict","sequence-conflict-does-not-poison-storage");
await bridge.StartAsync(default);await Wait(()=>runs.ContainsKey("first"));
JsonObject outputs=new();await Wait(()=>{outputs=Json(bridge.Outbox(server,world,default).GetAwaiter().GetResult());return outputs["items"]!.AsArray().Any(item=>item!["kind"]!.GetValue<string>()=="reply");});
Check(outputs["items"]!.AsArray().Any(item=>item!["kind"]!.GetValue<string>()=="progress"),"durable-progress-and-reply");
string firstConvo=runs["first"]["conversation_id"]!.GetValue<string>();
var reply=outputs["items"]!.AsArray().Single(item=>item!["kind"]!.GetValue<string>()=="reply")!;
string replyId=reply["output_id"]!.GetValue<string>();await bridge.Ack(replyId,server,default);await bridge.Ack(replyId,server,default);
await Error(async()=>{await bridge.Ack(replyId,"foreign",default);},"output_not_found","foreign-server-ack-denied");
await bridge.Accept(Input("held-current",2),default);await Wait(()=>runs.ContainsKey("held-current"));
Check(runs["held-current"]["agent_selection_initialized"]!.GetValue<bool>()&&runs["held-current"]["selected_agent_id"]!.GetValue<string>()=="owner-selected-agent","agent-snapshot-on-next-turn");
await bridge.Cancel(new JsonObject{["server_id"]=server,["world_id"]=world,["steam_id"]=steam,["source_run_id"]=run,["through_source_sequence"]=1L},true,default);
await bridge.Accept(Input("steer-current",3),default);await Wait(()=>steers.TryGetValue("held-current",out var queue)&&queue.Contains("steer-current"));
Check(!runs.ContainsKey("steer-current"),"stale-reset-cannot-open-parallel-owner-run");
var tool=new JsonObject{["task_id"]="held-current",["operation_id"]="tool-one",["name"]="player.position",["args"]=new JsonObject()};
await bridge.Tool(tool,default);await bridge.Tool(tool,default);Check(nativeCalls["tool-one"]==1,"reserved-tool-replay-never-executes-twice");
var conflict=tool.DeepClone().AsObject();conflict["name"]="grids.list";await Error(async()=>{await bridge.Tool(conflict,default);},"operation_id_conflict","tool-id-content-conflict");
completions["held-current"].TrySetResult(true);await Wait(()=>Json(bridge.Outbox(server,world,default).GetAwaiter().GetResult())["items"]!.AsArray().Any(item=>item!["source_sequence"]!.GetValue<long>()==3&&item["kind"]!.GetValue<string>()=="reply"));
Check(!runs.ContainsKey("steer-current"),"consumed-steer-is-not-replayed-as-new-run");
await bridge.Accept(Input("held-cancel",4),default);await Wait(()=>runs.ContainsKey("held-cancel"));
await bridge.Cancel(new JsonObject{["server_id"]=server,["world_id"]=world,["steam_id"]=steam,["source_run_id"]=run,["through_source_sequence"]=4L},false,default);
await Error(async()=>{var denied=tool.DeepClone().AsObject();denied["task_id"]="held-cancel";denied["operation_id"]="after-cancel";await bridge.Tool(denied,default);},"task_canceled","no-tool-admission-after-cancel");
Check(canceled.Contains("held-cancel"),"cancel-revokes-native-task");
await bridge.Accept(Input("second-owner",1,otherSteam),default);await Wait(()=>runs.ContainsKey("second-owner"));
Check(runs["second-owner"]["conversation_id"]!.GetValue<string>()!=firstConvo&&runs["second-owner"]["history"]!.AsArray().Count==0,"owner-conversation-history-isolation");
var session=await bridge.PrepareDetached(new JsonObject{["task_id"]="detached-one",["world_id"]=world,["steam_id"]=steam},default);
Check(Json(session)["prepared"]!.GetValue<bool>(),"detached-fresh-native-scope");
await Error(async()=>{await bridge.PrepareDetached(new JsonObject{["task_id"]="detached-one",["world_id"]=world,["steam_id"]=otherSteam},default);},"game_session_conflict","detached-task-cannot-change-owner");
await bridge.CloseDetached(new JsonObject{["task_id"]="detached-one"},default);
await Error(async()=>{var denied=tool.DeepClone().AsObject();denied["task_id"]="detached-one";denied["operation_id"]="closed-op";await bridge.Tool(denied,default);},"task_canceled","closed-detached-session-denies-tools");
var personal=new JsonObject{["steam_id"]=steam,["operation_id"]="personal-list",["action"]="list",["args"]=new JsonObject()};
var personalResult=await bridge.PersonalScriptTool(personal,default);Check(personalResult.ToJsonString()==(await bridge.PersonalScriptTool(personal,default)).ToJsonString(),"personal-library-operation-replay");
var personalBad=personal.DeepClone().AsObject();personalBad["action"]="deploy";await Error(async()=>{await bridge.PersonalScriptTool(personalBad,default);},"personal_library_action_rejected","personal-library-cannot-admit-game-mutation");
await bridge.StopAsync(default);bridge.Dispose();
bridge=new GameBridge();outputs=Json(await bridge.Outbox(server,world,default));Check(!outputs["items"]!.AsArray().Any(item=>item!["output_id"]!.GetValue<string>()==replyId),"ack-survives-bridge-restart");
Check(outputs["items"]!.AsArray().All(item=>item!["task_id"]!.GetValue<string>()!="detached-one"),"detached-result-never-enters-game-outbox");
await bridge.Accept(Input("after-restart",5),default);await bridge.StartAsync(default);await Wait(()=>runs.ContainsKey("after-restart"));
Check(runs["after-restart"]["agent_selection_initialized"]!.GetValue<bool>()&&runs["after-restart"]["selected_agent_id"]!.GetValue<string>()=="owner-selected-agent","agent-snapshot-survives-restart");
await bridge.StopAsync(default);bridge.Dispose();
using(var journal=new GameJournal(Path.Combine(root,"state","journal.sqlite"))){var state=journal.Load();var owner=state.Owners[server+"/"+world+"/"+steam];owner.LastUserAt=owner.LastFinalAt=DateTimeOffset.UtcNow.AddMinutes(-21).ToUnixTimeMilliseconds();await journal.CommitAsync(state,default);}
bridge=new GameBridge();string idleConversation=Json(await bridge.Accept(Input("idle-turn",6),default))["conversation_id"]!.GetValue<string>();await bridge.StartAsync(default);await Wait(()=>runs.ContainsKey("idle-turn"));
Check(idleConversation!=firstConvo&&runs["idle-turn"]["history"]!.AsArray().Count==0&&!runs["idle-turn"]["agent_selection_initialized"]!.GetValue<bool>()&&runs["idle-turn"]["previous_conversation_id"]!.GetValue<string>()==firstConvo,"twenty-minute-idle-rotates-conversation-and-agent-snapshot");
await Wait(()=>((GameBridge.State)typeof(GameBridge).GetField("state",BindingFlags.Instance|BindingFlags.NonPublic)!.GetValue(bridge)!).Tasks["idle-turn"].Status=="completed");
await bridge.Cancel(new JsonObject{["server_id"]=server,["world_id"]=world,["steam_id"]=steam,["source_run_id"]=run,["through_source_sequence"]=6L},true,default);
string resetConversation=Json(await bridge.Accept(Input("reset-turn",7),default))["conversation_id"]!.GetValue<string>();await Wait(()=>runs.ContainsKey("reset-turn"));
Check(resetConversation!=idleConversation&&runs["reset-turn"]["history"]!.AsArray().Count==0&&!runs["reset-turn"]["agent_selection_initialized"]!.GetValue<bool>(),"explicit-new-chat-resets-history-and-selected-agent-snapshot");
await bridge.StopAsync(default);bridge.Dispose();await app.StopAsync();await app.DisposeAsync();
File.WriteAllText("D:/semind-librechat/logs/game-bridge-checks.json",new JsonObject{["verified_at"]=DateTimeOffset.UtcNow.ToString("O"),["actual_game_inputs"]=false,["actual_game_actions"]=false,["checks"]=checks}.ToJsonString(new(){WriteIndented=true}));
Console.WriteLine("PASS: "+checks.Count+" isolated transactional bridge lifecycle checks; no actual game/model requests.");
